version: '3.8'

services:
  postgres:
    container_name: autoria-postgres
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - autoria-postgres:/var/lib/postgresql/data

volumes:
  autoria-postgres:
    driver: local